### ISSUE TITLE
error in config file

### ISSUE THREAD

**Issue by amouratoglou** [Code-Pop/build-a-blog-with-nuxt-3-and-nuxt-content-v2#3]
hi in order to get it up and running in my macbook I had to import defineNuxtConfig from 'nuxt/config'

`import { defineNuxtConfig } from 'nuxt/config'
`

**Comment by eharvey71** [comment]
I ran into the same issue. It appears to have not been fixed in the source yet.

**Comment by tutorialcode** [comment]
code updated
